### ISSUE TITLE
Make Transform GUI more user-friendly (based on feedback)

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#100]

**Comment by sharoncy** [comment]
- "Navigate to directory" button has same symbol as "save". This is confusing for users.
- Users were confused by the thumbnail feature (maybe move it somewhere else?), and by the resize factor (some confusion as to what a resize factor of 0.05 actually means... this is further confused by autoclipping as this also affects the image size).  
-Users have to request resize on the x and y axis for the transformation (some do not understand what size is obtained with x and y of 0.5 and 0.5 respectively). For the thumbnail feature size is specified with a resize factor. In the Resize operation size can be specified with resize percentage. We should choose one method for specifying the resizing and stick to it.  
-  Users says they would not be willing to type in new names manually in the Nutil template. Maybe add "advanced settings" dropdown with option to upload an excel template? The thumbnail feature could potentially be moved here.  
-

**Comment by Majpuc** [comment]
- Have info about not to run from desktop and speed performancies running local vs server
-implement a color picker for the spreading value
-have better examples of calculations for the resizing, flipping, etc..
-explain concept point clouds
- in the objects output files, avoid possibility to choose black or white background
- possibility to have output maps without numbers, only objects
-reports:have automatically the name of the atlas and name datset in each file
-tiff creator: how to choose tile size?
- confusing to have clear data and clear list next to each other

**Comment by sharoncy** [comment]
I am going to close this issue and transfer the relevant parts to other issues.
