### ISSUE TITLE
Update the default custom regions for rat

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#101]
Ingvild found a mistake in the default custom region file for rat. Replace this file with a corrected version.

**Comment by sharoncy** [comment]
Ingvild has provided a corrected version for both rat v2 and rat v3.

**Comment by sharoncy** [comment]
These files have been updated in Nutil, with a new version publised (v0.402).

**Comment by Majpuc** [comment]
Validated both WHSv2 and WHSv3 on 26.03.202o
