### ISSUE TITLE
Nutil crashing with more than 20 custom regions

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#105]
When I try running nutil with custom regions with many (120) custom region, it crashes. My experience is that around 20 regions work but no more. For the Allen atlas, it is essential to be able to create custom regions that are at a mid-hierarchy level so it will be important for quantifier to work with >20 regions. I attach the custom region file I'm trying to use.
[CustomRegions_Allen2017_IEB.xlsx](https://github.com/leuat/nutil/files/4323451/CustomRegions_Allen2017_IEB.xlsx)

(Please let me know if this seems like something that can be fixed relatively soon, or else I will have to split my custom region files into multiple ones and run several analyses per dataset for now)

**Comment by ingvildeb** [comment]
And directory of the files I'm using: Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\Calbindin\mouse10

**Comment by leuat** [comment]
yesss ser det nå. %(¤/% XLNT-library that we're using seems to have trouble reading and writing from columns larger than Z. I'll look into this - perhaps the best way is to add support for cvs files - in that case, you could export from excel and simply use those

**Comment by leuat** [comment]
AH nei! vent! var helt og holdent min feil! Fikset nå, kommer til å funke straks Sharon har pushet en ny versjon.

**Comment by ingvildeb** [comment]
Fantastisk, takk!
