### ISSUE TITLE
Allen regions with long IDs

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#107]
Some of the newer regions in the Allen CCF have very long ID strings. I noticed that these are sometimes wrong in the reports from quantifier. For example, the IDs for Laterointermediate areas all are listed as "312782592" in the report, but this is not the same ID as in the hierarchy file, where the different layers have different IDs (none of them have the one seen in the report). I've attached images of the report and the image from the same section. The images show the correct IDs and the report has objects counted in it, so I am not sure if this has any consequences, but I guess it should be checked out anyway. 

![report](https://user-images.githubusercontent.com/28010291/76860161-d817b880-685a-11ea-8209-1dd61ac52675.PNG)
![image](https://user-images.githubusercontent.com/28010291/76860163-d8b04f00-685a-11ea-9aa4-db6ba59d2eb4.PNG)

**Comment by sharoncy** [comment]
This needs looking into - I'm not sure what is going on.

**Comment by leuat** [comment]
@ingvildeb : in order to reproduce this bug, I'll need a setup to test on. Could you zip & send me the project data, preferably where you've removed all but 1 of the slices? And then point out exactly what is wrong, so I can go through the process step-by-step

**Comment by ingvildeb** [comment]
[long_ids_problem.zip](https://github.com/leuat/nutil/files/4393200/long_ids_problem.zip)

Here is a zipped folder. I copied only one image (the one shown and described above) into the input and atlas directories. I copied the output image and all reports to the output dir. As mentioned, the really long IDs are right in the images, but wrong in the reports. Maybe it has something to do with excel making exponential numbers out of the really long numbers, so that when they are converted back they get wrong? I only noticed this because I was going through the hierarchy file and report file at the same time, but I don't have a complete overview of how many regions this affects.

**Comment by leuat** [comment]
Puh, took some time to identify, but finally fixed! Problem was that I at one point in the report system was using 32-bit floats for representing the ID's, which yielded a rounding error when going back to longs afterwards... thanks for the bug finding!

**Comment by sharoncy** [comment]
Ingvild has validated this.
