### ISSUE TITLE
Transform: Replace folder icon with button titled "browse ... "

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#108]
![browse](https://user-images.githubusercontent.com/30626642/76928379-95e58a00-68e1-11ea-82e5-0e38ef76bc03.PNG)
The feedback from the data curators was that the folder icon on the Transform GUI is confusing as it means "save". I have looked a bit online and think the best would be a button with "browse ..." as in the picture above. This seems most logical to me, but feel free to add something else if you disagree.

**Comment by Majpuc** [comment]
Yes, better.

**Comment by leuat** [comment]
Done

**Comment by sharoncy** [comment]
I changed it from "..." to "Browse...". Hope you don't mind! This is obviously up for debate.
