### ISSUE TITLE
Transform: Add "show advanced settings" below the Tranform template.

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#109]
The data curation team were confused by the "only generate thumbnails" feature. They did not think it was logical that the thumbnails are generated from the transformed images. This would be more logical if the thumbnails option falls after the transform template. 

To make this more understandable, I suggest adding "show advanced settings" below the transform template and moving the "generate thumbnails" and "thumbnail size" in there. We should also add the option to upload a word document here for definiting the transformation settings. I will add this as a separate issue.

**Comment by Majpuc** [comment]
Agree.

**Comment by leuat** [comment]
Done

**Comment by Majpuc** [comment]
Validated 26.03.2020
