### ISSUE TITLE
Transform: Add option to upload a excel template for defining the transformations

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#110]
Under "add advanced settings" in Transform, give users the option to navigate to a word document for defining the input/output folder names and transformation settings (this was a big request from the curation team, they said they would not have the patience to type in new file names manually). The code should be updated to work with a cleaned up version of the transform template, something like this:
Z:\HBP_Analytics\Nutil\Nutil_releases\Resources_for_Nutil\Transform_template\TransformTemplate.xlsx

Again, feel free to suggest something else if you have a better idea.

**Comment by Majpuc** [comment]
Why a Word document? They have been using Excel all the time.

**Comment by sharoncy** [comment]
My bad, I meant Excel!

**Comment by sharoncy** [comment]
Nicolaas' suggestion was to implement support for importing contents of the template into the GUI. This is a good idea.

**Comment by sharoncy** [comment]
A "from excel" button has appeared in Nutil Transform but it doesn't work yet. This should be fixed ASAP.

**Comment by sharoncy** [comment]
Sharon will provide a template

**Comment by leuat** [comment]
Implemented. The "From Excel" button will *insert* data from the excel template but not delete existing data (so you can choose to merge from several excel documents etc). I've therefore added a "Clear data" button as well.

**Comment by sharoncy** [comment]
Great. I'll test.

**Comment by sharoncy** [comment]
I found a small error but fixed it and have pushed back to github. Works great!
