### ISSUE TITLE
Transform: make background colour/ colour spread feature more understandable

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#111]
The feedback from the curation team was that is difficult to work with the background colour /colour spread feature as they are not used to working with RGB colour codes (for example, don't have any background knowledge about what 245,245,245 looks like). They asked if there was any way to have a colour picker for the spread feature, or a way to visualise the range (currently, they enter numbers at random and hope it will work, but it is time consuming if it doesn't). 

I haven't had time to give this too much thought, maybe you have some ideas Nicolaas? Something user friendly/ intuitive for people with no background of working with colour codes....

**Comment by Majpuc** [comment]
Here, the curation team suggested to have a color picker from the actual image they want to transform.

**Comment by leuat** [comment]
Ok, so for simplicity:  imagine that an image is defined by a single value between 0-255. You're now asked to define a "background" color. Let's say that the background colour is max intensity - so you define value 255 as the background. 

But wait! What if your background colour has some noise in it? some slight variation? A couple of pixels extra... this becomes really bad when trying to auto crop. So If we now define a colour "spread" value of 10, all values between 245 and 255 will be considered as the background.

Extend to 3 values RGB, and you've got our system. I realize that we should probably replace the names with "Background colour range: Start RGB and end RGB". In that case, the user can define things like the background to be any values between (240,240,220) - (255,255,255), which is probably a bit more intuitive. What do you say?

**Comment by sharoncy** [comment]
I reordered the features in the template and improved the help text. I am open to suggestions on how to improve it further.

**Comment by Majpuc** [comment]
@sharoncy Can you add the word "range" in the help text as suggested?

**Comment by sharoncy** [comment]
Will do.

**Comment by sharoncy** [comment]
I changed the text to "background colour range", and updated the help text. To allow users to enter Start RGB and end RGB values (rather than just a range like 5) the template needs restructuring, which needs input from @leuat

**Comment by Majpuc** [comment]
We will settle with help text for now.

**Comment by sharoncy** [comment]
I have checked the descriptions and they are ok. This is validated.
