### ISSUE TITLE
Transform: resize factor/ size / type

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#112]
Currently resize factor/image size is specified differently in different parts of Nutil. For example, in the "Resize" feature, it is specified with "resize type" and "resize factor". In transform, it is "thumbnail size". Biologists do not have a good understanding of what resize factor means (for example, don't necessarily understand that they should enter 0.5 for 50%)...

 I think the "resize type" (select between percentage and pixel width) and "output size" in the Resize feature is more logical for biologists than resize factor. As I requested in another issue, best to move the "Transform: thumbnail feature" under "advanced settings" and implement the same format for specifying the output size as in "Resize" (drop down menu for percentage and pixel width with separate field for entering the no). Again, I haven't had much time to think this through, so am open to other suggestions!

**Comment by Majpuc** [comment]
I would suggest a small brain storm session with the Curation team

**Comment by sharoncy** [comment]
We have decided to stick with x/y scaling, it needs to be explained better in the help text, with example images etc.

**Comment by sharoncy** [comment]
I will close this issue as this has been lifted over to issue 123 (improvement in help text needed).
