### ISSUE TITLE
Not all custom regions are in reports

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#114]
I tried the new version for many custom regions, it does no longer crash, but it also does not extract all my custom regions to the reports. Specifically, it seems to exclude all those listed between (and including) columns AA and AZ in the excel sheet. Those after that (from BA onwards) are extracted.

**Comment by sharoncy** [comment]
Thanks for the info @ingvildeb . We'll look into it.

**Comment by leuat** [comment]
My bad. Fixed!

**Comment by sharoncy** [comment]
Validated by Ingvild on 27.03.20
