### ISSUE TITLE
Nutil closes down when using for a while and loading consecutive jobbs

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#116]
Nutil closes down (crashes?) when I am doing several different jobbs after each other. It seems it needs to be reopened regularly. Why is that?

**Comment by leuat** [comment]
I need to be able to reproduce the error in order to fix it. Is it quantifier or transforms? how much time? Could you point to a list of nut files that you've been running, in what order etc in order to reproduce the error.

**Comment by Majpuc** [comment]
Yes, it is quantifier and I had Nutil open for more than one hour, going back and forth testing several dataset. Everything is on the Nesys server but I can zip and send to you.

**Comment by leuat** [comment]
This issue is merged with #132
