### ISSUE TITLE
Two identical Quantifier analyses give slightly different output

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#117]
I have sent Nicolaas a zipped folder with an example dataset, but here is an example of difference between two sets of reports from identical analyses:

Test1
![Test1](https://user-images.githubusercontent.com/30626642/79727985-82b54800-82ed-11ea-97ff-27e26de4264a.PNG)

Test2
![Test2](https://user-images.githubusercontent.com/30626642/79727989-8517a200-82ed-11ea-8cc5-a1d22451e949.PNG)

**Comment by leuat** [comment]
Fixed! Turned out to be a simple floating point error. When summarizing over the areas, everything is scaled down to ~1, meaning that some of the values were *way* below the limit of floating point numbers. When multiplying with a large number again (like the pixel area), the error was magnified. Switching to 64-bit double fixed the issue! Please verify.

**Comment by sharoncy** [comment]
Thanks for looking into this. I did a test and looks like it's still happing. Maybe more to it? 
I pulled, cleaned and did a QMake to make sure... see output from identical tests below:
Test 5
![Test5](https://user-images.githubusercontent.com/30626642/79981793-90153280-84a5-11ea-974c-1243556020fe.PNG)

Test 6
![Test6](https://user-images.githubusercontent.com/30626642/79981804-93a8b980-84a5-11ea-8af6-1025c660fe2b.PNG)

The output for region pixels and region area should be the same as I entered a pixel scale of 1. I highlighted the rows where these differ.

**Comment by sharoncy** [comment]
Also, think it would be fine for the reports not to display decimal places for the region pixel and region area columns.

**Comment by leuat** [comment]
Are you sure the pull went through? Please pull again, and see if you get any error messages... because I'm pretty sure that this should be fixed!

**Comment by sharoncy** [comment]
Performed 22.04.20
Test 5
![Test5](https://user-images.githubusercontent.com/30626642/80101367-97097700-8571-11ea-9598-2fefc7dcf812.PNG)
Test 6 
![Test6](https://user-images.githubusercontent.com/30626642/80101384-9cff5800-8571-11ea-8236-e422e273739f.PNG)

Performed 23.04.20
Test 7
![Test7](https://user-images.githubusercontent.com/30626642/80101400-a25ca280-8571-11ea-9737-955b7483cd00.PNG)
Test 8
![Test8](https://user-images.githubusercontent.com/30626642/80101413-a7215680-8571-11ea-8233-b18efe86d258.PNG)

**Comment by sharoncy** [comment]
Nicolaas gets identical results on his linux computer so it might be a problem introduced by compiler optimisation on Windows.

**Comment by sharoncy** [comment]
Nicolaas fixed this. It was a mulithreaded / MPI  issue that was different on windows that linux. I have validated: 
Test 13
![Test13](https://user-images.githubusercontent.com/30626642/80953749-6db3db00-8dfc-11ea-82f4-f29ee7949da3.PNG)

Test 14
![Test14](https://user-images.githubusercontent.com/30626642/80953766-73a9bc00-8dfc-11ea-9777-e6047c3584f6.PNG)
