### ISSUE TITLE
Label files missing?

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#12]
Hei,

I cannot see the atlas label files in the package...

**Comment by leuat** [comment]
Please provide a link to label files that should be included!

**Comment by Majpuc** [comment]
I get a message that this type of files is not supported to paste in here. I will come with them on a god old memory stick;)

**Comment by sharoncy** [comment]
The mouse and rat label files have been sent to Nicolaas in an email. Please upload to NITRC. I have updated the NITRC wiki to include the necessary citations.
