### ISSUE TITLE
Quantifier Images: output maps without the numbers, only objects.

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#124]
THe curation team requested that Quantifer generates output images without the RefAtlasRegion IDs. The images with the IDs are very useful for problem solving, so we would like to keep these too. The ones without IDs would be good for articles, etc. I suggest generating two sets and sorting them into two folders within the "Images" folder. 
![tg2576_m287_1D1_s002_resize_Object Predictions](https://user-images.githubusercontent.com/30626642/80573707-c2bcaf00-8a00-11ea-9c97-bb7e9a8bcf92.png)

**Comment by leuat** [comment]
This has been implemented as a drop-down yes/no option.

**Comment by sharoncy** [comment]
@leuat Thanks. I'll test. The drop down menu complicates the GUI, I need to improve the help text/description, but we could discuss if there are other options here (e.g. automatic generation of two sets of images without options for switching on and off ID text, this would remove the need for a drop down). Lets discuss @Majpuc

**Comment by Majpuc** [comment]
@sharoncy  where in the GUI would this be visible?

**Comment by sharoncy** [comment]
This is how it looks in the version that hasn't been published yet, "write region ID text to image files", located under advanced settings:
![Image_1](https://user-images.githubusercontent.com/30626642/82028623-2ea44600-9696-11ea-8f8c-a5a9b6cf7bc5.PNG)

**Comment by Majpuc** [comment]
This is fine. Let's test it!

**Comment by sharoncy** [comment]
It's tested and works fine.
