### ISSUE TITLE
Error message in Transform v4.02

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#131]
Hi,
I am trying to flip a Tiled Tiff iamge but get this error message
![bilde](https://user-images.githubusercontent.com/46992863/83532763-00749200-a4ef-11ea-8641-afaf76d5dd10.png)
[IL-33nut.txt](https://github.com/leuat/nutil/files/4717801/IL-33nut.txt)
Raw image located here: Z:\NESYS_Active_projects\2020_IL33_Rodent-Haraldsen\M6001

**Comment by Majpuc** [comment]
Made another test: Nutil run locally and image stored locally. Works perfectly!
error certainly related to internet connection!

**Comment by Majpuc** [comment]
Z:\NESYS_Active_projects\2020_IL33_Rodent-Haraldsen\M6001\M6001_s005

**Comment by sharoncy** [comment]
Merge with #132. Server problem
