### ISSUE TITLE
General issue for server errors (Nutil running unstable on the local UiO network)

### ISSUE THREAD

**Issue by leuat** [leuat/nutil#132]
This is a common issue for all errors that are linked to "problems running Nutil over the network". There seems to be an issue with the NeSys servers whenever large .tiff files are being opened and treated over the network.

**Comment by sharoncy** [comment]
I ran a transform test with images located on the "lagringshotell" that are known not to be corrupted with Nutil on the C drive and it successfully transformed all images (>100 images, took 6 + hours). It looks like the server problem fixed, at least for now.
