### ISSUE TITLE
ICON files for Nutil (Windows / macos)

### ISSUE THREAD

**Issue by leuat** [leuat/nutil#133]
We need a nice icon file for the Nutil application. It needs to be the size of the attatched file - creating a small newt would probably look amazing!

![trse_icon](https://user-images.githubusercontent.com/5620670/83750622-d7c2d880-a665-11ea-97f0-a2f896999a08.png)

**Comment by Majpuc** [comment]
![Nutil_logo_128](https://user-images.githubusercontent.com/46992863/83755169-6edf5e80-a66d-11ea-8004-919c793dfd5f.png)

**Comment by sharoncy** [comment]
Icon looks good on windows and mac.
