### ISSUE TITLE
Suggestion - option to distribute coordinates at random in one specific plane

### ISSUE THREAD

**Issue by marovst** [leuat/nutil#134]
I wish to represent point-clouds extracted from 2D sections displaying its original section thickness (e.g. with a sectional thickness of 100micron, the coordinates should be distributed up to 50microns from the coordinate plane). Extracted coordinates will then appear as a homogeneous cloud (100 micron thick), not a 2D cloud-plane, like it does today. In nutil this could appear as an option/check-box which distribute coordinates at random with a set distance. This option will help researchers to better visualise and qualitatively analyse data shown in 3D together with the recently developed cutting tools in MeshView.

**Comment by marovst** [comment]
Hi!

Have you been able to work on this issue? Is there anything I can do to help progressing?

**Comment by sharoncy** [comment]
I'll look into this and get back to you @marovst .

**Comment by leuat** [comment]
Implemented!

**Comment by sharoncy** [comment]
The feature has been implemented in the code but not properly in the GUI. I will run some tests and send you some example output @marovst before I publish this on Nesys. It may need some tweaking to meet your needs.

**Comment by sharoncy** [comment]
I have implemented the feature properly in the GUI and updated the version number to 0.404. But I am having trouble publishing Nutil on the server. Not sure what is happening! Let's look at this tomorrow @leuat.

**Comment by sharoncy** [comment]
I got it to work, was something with my laptop.

**Comment by Majpuc** [comment]
@marovst Can you confirm if this is working properly?

**Comment by marovst** [comment]
@Majpuc I got it to work as intended, thank you for the help.
