### ISSUE TITLE
Transform with excel sheet as input

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#138]
I am trying to use Transform with the "From Excel" option in Nutil 0.402, but nothing happens when I click the button. Also, there is no excel template in the newest  package. @leuat @sharoncy

**Comment by sharoncy** [comment]
That feature was only half implemented in that version. It's fully implemented in Nutil 0.403 v6. You can find it on our server here: HBP_Analytics\Nutil\Nutil_releases\Nutil_v403_v6. But great that you point these things out!

**Comment by Majpuc** [comment]
@ingvildeb is the issue solved when using the released version of nutil 0.403?

**Comment by ingvildeb** [comment]
Yes, I started using it now and it works well (actually using NUT files made in v.403 but running them in v.402). I can try to run in v.403 tomorrow!

**Comment by Majpuc** [comment]
@ingvildeb very nice! Can you confirm everything is working now?

**Comment by ingvildeb** [comment]
Yes, everything is working well!
