### ISSUE TITLE
Trouble Running ilastik Software

### ISSUE THREAD

**Issue by howardli123** [leuat/nutil#139]
Hello, 

I have the latest version of the ilastik software installed, the software upstream of nutil in your QUINT pipeline. However, when trying to run the program, an error occurs. I have tried to attach a screenshot of the error but am unsure if it will show up. The error heading reads "python.exe - Ordinal Not Found" and the error message reads "The ordinal 191 could not be located in the dynamic link library libiomp5md.dll." Are there any steps I can take to fix this? Thank you so much!

![Screen Shot 2020-06-19 at 4 13 39 PM](https://user-images.githubusercontent.com/66743784/85176832-bc042880-b248-11ea-96ed-86c93a9d905d.jpg)

**Comment by sharoncy** [comment]
Hi, thanks for your interest in the workflow! We are not directly involved in the development of ilastik, but ilastik issues can be reported here: https://github.com/ilastik/ilastik/issues
I hope you find a solution!
Sharon Yates
