### ISSUE TITLE
Nutil Transform - autocropping

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#17]
Nicolaas has fixed a bug in autocropping but Maja has not yet tested. This should be tested before the next official release.

**Comment by Majpuc** [comment]
the autocropping function is not working properly

**Comment by sharoncy** [comment]
This should be tested before closing.

**Comment by Majpuc** [comment]
The clip files are still not removed (14.01.2020)

**Comment by leuat** [comment]
I guess this is fixed by now

**Comment by Majpuc** [comment]
Issue moved to ticket#71
