### ISSUE TITLE
Nutil Transform - resize factor with "only thumbnails" 

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#18]
Ingvild has found a bug in Nutil Transform. Nutil applies a different resize factor to images depending on whether "Only thumbnails" is switched on or off. Ingvild can describe the problem in more detail.

**Comment by ingvildeb** [comment]
When I use Transform with renaming and tuhmbnails, the thumbnails end up much smaller than when I use Transform with the "Only thumbnails" option. When I use "Only thumbnails", the selected resize factor is applied to the pngs. But when I use thumbnails together with renaming, it seems that it resizes a lot more (in the cases I've looked at, looks like final size is about 50% of the selected resize factor). The original images are of similar size.

**Comment by ingvildeb** [comment]
I think I realize now what happened, mainly me being stupid. 
I generated 50% tiffs at an early stage and therefore had the Scale X and Scale Y set to 0,5. I guess this is applied to the thumbnails as well when the renaming feature is used. I didn't realize. 

I still think the factor added in thumbnail size should correspond to the final thumbnail size regardless of whether or not the user chooses to scale the tiffs? Or else, it should be explained in the template that when scaling the original files, this will also apply to the thumbnails?

**Comment by sharoncy** [comment]
The thumbnail function makes thumbnails of the Transform output rather than thumbnails of the input. This is not logical for the user. Maybe discuss this with Maja, etc.

**Comment by leuat** [comment]
So... can we close this one?

Assume you take a picture with your fancy camera. You then process the picture, removing some stuff, altering the colours etc. You now want to make a thumbnail of the image. And, naturally, you'd like a thumbnail of the *processed* image, not the original one. 

Why would you even want this? The pre-processed thumbnails have incorrect rotation and clipping etc... can we close this?

**Comment by Majpuc** [comment]
Actually, we still get two different thumbnails depending if we choose thumbnail only yes or no.
![bilde](https://user-images.githubusercontent.com/46992863/72736735-8f1aef00-3b9e-11ea-86c4-c15f06b5b00b.png)
![bilde](https://user-images.githubusercontent.com/46992863/72736770-9f32ce80-3b9e-11ea-9338-ed5240e57c99.png)

**Comment by Majpuc** [comment]
Do you need the nut files?

**Comment by Majpuc** [comment]
Here are the two files when no rotation if asked for
![bilde](https://user-images.githubusercontent.com/46992863/72805007-27be7700-3c52-11ea-8800-51636abd859c.png)

**Comment by Majpuc** [comment]
The reason for this difference was the autocropping function. If yes is chosen, the resulting thumbnail will be autocropped. Issue closed.
