### ISSUE TITLE
Quantifier crashing with rat data

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#22]
Nutil crashes when I try to use quantifier for rat data. It works for a while, but then suddenly stops. I get the superimposed atlas / segmentation images in the output folder, and they seem to be fine. I've tried running it several times, and sometimes it seems that it gets through making all the images but sometimes not. No reports are created.
![nutil-crash](https://user-images.githubusercontent.com/28010291/59742612-6f20f700-926e-11e9-90da-09a4ff9d009d.PNG)

**Comment by leuat** [comment]
Yo! this is excellent, making Nutil crash in this way will help us preventing this issue in the future. However, I will need the nesys folder where the data resides, so I can try to reproduce the error

**Comment by ingvildeb** [comment]
Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\PVRat_25206

**Comment by leuat** [comment]
Found the bug, difficult one to track down, but fixed it. Will be released in a new beta release tomorrow.
