### ISSUE TITLE
With mask - bug in output report

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#23]
I did a quick Nutil test with and without masks and compared the report.csv output. The output for object area was approximately halved (reflecting use of mask), but the output for region area was the same in both reports. The region area calculation should take into account the mask. This needs a more indepth test.

**Comment by sharoncy** [comment]
For the output reports the mask should be applied to both the segmentations and the atlas maps.

**Comment by leuat** [comment]
Has been implemented, but needs testing after release on friday.

**Comment by sharoncy** [comment]
I have tested with masks and compared R/L total to WB for RefRegions and CustomRegions. All correct. Do I need to do more detailed validation?

**Comment by Majpuc** [comment]
Validated enough for R\L 21.01.2020
