### ISSUE TITLE
No. of decimal places used for calculations

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#25]
The different versions of the reports vary slightly in the total no. of pixels reported (not significantly, but users might get confused), I suspect this is because of differences in no. of decimal places used in  calculations. Is there a way to standardise this so that the outputs are consistent?

**Comment by sharoncy** [comment]
Question:
No. of pixels displayed with decimal places in report_slices_summary.xlsx. Why?
The .xlsx and .csv reports round up differently (diff. no. of decimal places used)

**Comment by Majpuc** [comment]
There are small differences in region pixel output for identical analyses. Why? Rounding up error?

**Comment by sharoncy** [comment]
@sharoncy should replicate this problem and provide an example dataset

**Comment by sharoncy** [comment]
Test 7
![Test7](https://user-images.githubusercontent.com/30626642/80100879-e4d1af80-8570-11ea-8b96-0fc5aad98684.PNG)
Test 8
![Test8](https://user-images.githubusercontent.com/30626642/80100893-eb602700-8570-11ea-9136-05d30029c57c.PNG)

**Comment by sharoncy** [comment]
I'm closing this issue as it is the same as #117.
