### ISSUE TITLE
Max object size in Quantifier

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#29]
Quantifier currently divides objects larger than the max size into objects of max size or less... I can't remember exactly why this was implemented but it not easy to understand for the user and gives false object counts. We should discuss this to find another solution....

**Comment by sharoncy** [comment]
We discussed this and Nicolaas will implement a real max object size (all objects above this size will be excluded from the analysis).

**Comment by sharoncy** [comment]
Check if this is done. I am writing the help text for the new GUI so need correct info.

**Comment by sharoncy** [comment]
The object_s001_csv have a column titled "cutoff reached". This should be removed if a real max object size has been implemented.

**Comment by sharoncy** [comment]
Nicolaas has implemented a real max object size cutoff.

**Comment by Majpuc** [comment]
To test with the atlas map dataset

**Comment by Majpuc** [comment]
@sharoncy  which dataset can be used to validate this?

**Comment by Majpuc** [comment]
Closed issue on 11.03.2021. open a new ticket if issue reappears.
