### ISSUE TITLE
Request export of summary json and slice json

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#3]
I would like the option to request either a summary json (all points) or individual json files per slice. I would also like the option to adjust the density of the points (extract coordinates for every other pixel, every 4th pixel, etc).

**Comment by leuat** [comment]
Fixed individual slices in the beta version, density of point still in progress. Please update the template with options "Yes", "No", "Slices", "Summary", and provide feedback if it works! Released with beta version 0.3202.

**Comment by sharoncy** [comment]
I tested with option "slices" with an updated version of the template, but didn't get any coordinate output. Did you release? Nutil says v0.3201.

**Comment by lillemoo** [comment]
I tested with option "yes" on XYZ file, but did not get any coordinate output. However, I got atlas overlay on all the images. Used updated version of the template and nutil (v0.3203). Test files: binary images from Allen Institute, 140 .pngs, 3998x2998

**Comment by sharoncy** [comment]
I looked again this morning and it doesn't seem to work. Let's look at this when you're in.

**Comment by sharoncy** [comment]
This is now implemented.
