### ISSUE TITLE
AMBA hierarchy xlsx - incorporate this in the Nutil package on NITRC

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#31]
It is not really possible to create custom regions without this file. Should we add it to the Nutil package? This need discussion as @Majpuc had some concerns.

**Comment by Majpuc** [comment]
Yes, include that file

**Comment by Majpuc** [comment]
Hi guys!!
Actually QuickNII comes with both AMBA 2015 and 2017 versions!!! We need to accomodate for multiple versions!!!

**Comment by sharoncy** [comment]
Maja has requested that Gergely creates a hierarchy file for the 2017 version. These hierarchy files should be included in the Nutil package on NITRC.

**Comment by sharoncy** [comment]
Gergely has sent me hierarchy file.
