### ISSUE TITLE
Flipping and rotating with transform

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#39]
It seems that "scale X" flips horizontally and "scale Y" flips vertically, contrary to the indication in the excel sheet. Not sure if this is something that should be changed in the template or in the code? 

Also, it should be clear from the excel sheet whether rotation or mirroring occurs first, since the order might affect the final result. I will check soon which one happens first.

PS- I find entering the rotation in counter-clockwise direction to be less intuitive than clockwise. I also think clockwise is what is actually happening? When I enter "Rotation CCW" of 90 degrees, the image on the left is transformed to the one on the right.

![image](https://user-images.githubusercontent.com/28010291/63502361-b7a69c00-c4cd-11e9-81a3-c438e805cdd2.png)

**Comment by leuat** [comment]
I guess this needs to be clarified in the help text

**Comment by Majpuc** [comment]
changes in GUI help text in order to explian. Working properly. Validaded MAP 21 jan 2020
