### ISSUE TITLE
Create help text for new GUI

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#44]
Create help text for the new GUI entries

**Comment by leuat** [comment]
I guess this is completed by now?

**Comment by Majpuc** [comment]
Almost ;)

**Comment by sharoncy** [comment]
To revise:
Transform help text for:
- compression
-image background colour
-background colour spread
-list of images
- column titles (x and y scale) (Nicolaas' input required for this)

**Comment by sharoncy** [comment]
To revise:
Help text for masks in Quantifier

**Comment by sharoncy** [comment]
x and y scale is fixed.
masks are done.
compression type: ask Nicolaas for input.

**Comment by Majpuc** [comment]
@leuat Do you have info text about the compression types that we can put into the help text?

**Comment by sharoncy** [comment]
This is an ongoing issue. I will close this issue and create separate issues for each individual help text request to make it easier to manage.
