### ISSUE TITLE
Report file naming

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#45]
Foreslår at rapportene kan få navn som inneholder navnet på datasettet. Dersom man skulle ønske å åpne flere rapporter fra ulike datasett for å sammenligne disse har de nå samme navn og excel kan ikke åpne to filer med samme navn. Kan selvsagt bare renames manuelt, men tror det er fint med datasett-navn i tittelen (også for å holde orden på filer).

**Comment by sharoncy** [comment]
This is a good idea. We'll look into implementing this next time we make changes to the reports.

**Comment by leuat** [comment]
I guess this has been taken care of, with the new directories etc?

**Comment by sharoncy** [comment]
Ideally the name of the project should be added as a prefix to all the reports/coordinate files, etc. Otherwise it's hard to open and compare reports from different analyses.

**Comment by sharoncy** [comment]
This is tested and validated.
