### ISSUE TITLE
Request for RefAtlasRegion slice reports - these are not currently generated

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#61]
-Where are the RefAtlasRegion per slice reports? These should be incorporated in the RefAtlasRegion all xlsx

**Comment by sharoncy** [comment]
This has been implemented so that slice reports are generated but they still need some restructuring/ altering

**Comment by sharoncy** [comment]
This has been fixed. There are several issues with the file formats but this has been added as a separate issue.

**Comment by Majpuc** [comment]
Validated Sharon 21.01.2020
