### ISSUE TITLE
Quantifier: request to display masks in the output images

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#62]
-When using masks display them in the output image (maybe black out everything that isn't included in the analysis? or display mask in white and eveything else in grey..?)

**Comment by leuat** [comment]
Fixed. Masked areas are now presented with a black dithered overlay pattern

**Comment by sharoncy** [comment]
- I did a test of the mask feature with analysis type "none" (no QuickNII input). Everything looks great except the report names. The names should be updated to reflect no QuickNII input (currently titled: RefAtlasRegion, CustomRegion and Object). Just "Regions" would work... Also, there should be no coordinate file generation.

- Some of the settings are not relevant for analysis type "none"  (e.g. customised reports, nifti size, pixel density, coordinate extraction). There should be conditional display of these settings.

**Comment by sharoncy** [comment]
I am going to close this issue and add the remaining issues as separate issues.
- improve mask help text
- support for double conditional display (eg. for the customised region file)
- test report names with analysis type "none".
