### ISSUE TITLE
"Trying to access atlas index: " - cannot find the correct atlas region

### ISSUE THREAD

**Issue by lillemoo** [leuat/nutil#68]
Description of the problem:
I can run the program and start the analysis like before, but when it have "100%" on "finding areas" the process goes into a loop with the following text:

Trying to access atlas index :  XXXX  which is above  1288

This have not happened before with similar image data. 

Text file with nutil specifics:
[Test_low_2.txt](https://github.com/leuat/nutil/files/3978792/Test_low_2.txt)

**Comment by sharoncy** [comment]
Problem: Martin used the 2017 version of the AMBA atlas, but selected AMBA 2015 in Nutil. 
Solution: The 2017 version has now been incorporated in Nutil. This has been tested and works.
