### ISSUE TITLE
Request for batch processing of Quantifier .NUT files

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#70]
Martin has a lot of data to process. He has requested a more efficient way to run analyses, for example by batch processing of .NUT files.

**Comment by sharoncy** [comment]
As a short term solution Nicolaas will write a script for batch processing .NUT files. In the long run we may look into implementing a more user friendly solution in Nutil.

**Comment by leuat** [comment]
Nutil currently supports command-line parameters. You can run nutil as such:

nutil.exe my_file.nut 4   

where "4" implies the number of threads

**Comment by Majpuc** [comment]
Validated by Martin jan_2020
