### ISSUE TITLE
Transform GUI - template for entering parameters disappears

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#71]
The template for entering transformation parameters disappears on selecting "New".

**Comment by leuat** [comment]
Fixed

**Comment by Majpuc** [comment]
As reported the template disappears if changing compression type. Test_20_01_2020 MAP

**Comment by Majpuc** [comment]
This is happening when you change the dropdown options

**Comment by sharoncy** [comment]
Fixed
