### ISSUE TITLE
Improve template for entering Transformation parameters 

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#72]
Improve usability of the template for entering transformation parameters. 
- implement copy/pastes or drag down to apply parameters to all images.
- improve appearance of title column (cannot read the full text)

**Comment by leuat** [comment]
1) Added a "duplicate" button that duplicates current data cell to all columns w/warnings
2) Title appearance changed
3) also added "disk" icon instead of "Select directory" in order to save space

**Comment by Majpuc** [comment]
Validated 21 jan 2020
