### ISSUE TITLE
Resize not running

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#75]
I get error message:""
"LOG: ******** Reading global header"
"LOG: ******** Type of Nutil operation: Resize"
"LOG: ******** Reading local header"
NutilTemplate::Get error : could not find item for value ' "output_compression" '
"LOG: ******** Building"
"MESSAGE: Required memory: 0 GB. Free memory : 32651 GB from a total of 32651 GB installed (0 %) usage"
"LOG: ******** Executing"

NutFile:
type = Resize
name = 
resize_output_compression = jpeg
resize_input_dir = E:/AD tg rat_tiffs/TG5173
resize_output_dir = E:/AD tg rat_tiffs/Thumbnails TG5173
resize_size = 25
resize_type = Percent

**Comment by leuat** [comment]
Fixed
