### ISSUE TITLE
Transform "list of images" - table disappears 

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#77]
The table for entering transformation parameters disappears on selecting "New" "Transform".

**Comment by leuat** [comment]
hm... I need some more details in order to reproduce this bug. doesn't happen here

**Comment by sharoncy** [comment]
It happened this morning in Qt. But now I'm failing to reproduce it too... hmm.. strange

**Comment by sharoncy** [comment]
I'll let you know if it happens again

**Comment by sharoncy** [comment]
Maja has also had several occurrances of this issue. She will give more detail.

**Comment by sharoncy** [comment]
This issue is the same as issue 71. I will therefore close this one.
