### ISSUE TITLE
Quantifier Customised reports - no, default, custom

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#78]
- Change the options in the drop down menu to "no", "default" and "custom".

- For default, link to the atlas version (one customised region file per atlas, information about this should be included in the user manual). We need a different one for each version of the atlas (currently: WHS v2, WHS v3, AMBA 2015 and AMBA 2017). We have one for AMBA 2015. All the others need to be created and implemented.

**Comment by sharoncy** [comment]
Creating the files is a task for Sharon/Maja. We need the 2017 hierarchy file from Gergely before we can look at this. The rat version should be updated to include all the atlas regions (not just a subset as applies to the one Ingvild created).

**Comment by leuat** [comment]
Parameter name has been changed to "default"

**Comment by sharoncy** [comment]
I have created a default for AMBA 2015 and 2017.

**Comment by sharoncy** [comment]
Default files are made.

**Comment by sharoncy** [comment]
I have removed the "no" from the list as Nutil does not generate coordinate files unless a custom region file is included. THe options are now limited to "default" or "custom".

**Comment by Majpuc** [comment]
Validated 26.03.202
