### ISSUE TITLE
Error message on opening Nutil - extraction colour bright green...

### ISSUE THREAD

**Issue by Majpuc** [leuat/nutil#79]
![bilde](https://user-images.githubusercontent.com/46992863/72732463-0ef08b80-3b96-11ea-87f6-d5ff3f65ce1b.png)

**Comment by sharoncy** [comment]
- These are two separate issues. The error messages are to do with the two mirroring PNG images in the software. Nicolaas suggested removing them, saving in photoshop and reapplying to see if it fixes the error messages.

- The green colour originated from an old NUT file. I deleted the old NUT files and this fixed the problem.

**Comment by sharoncy** [comment]
I removed the mirroring icons and edited them with photoshop (changed from rgb to grayscale) and then reuploaded to Nutil. This did not fix the libpng warning: iCCP: known incorrect sRGB profile.
