### ISSUE TITLE
Automatic test dataset generation - should we switch this off before release?

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#84]
Currenty a test dataset is automatically generated on Nutil download. This was implemented for internal use. Should we switch off this feature for the external release? Or activate the button for test dataset generation?

**Comment by Majpuc** [comment]
It is a bit odd with the tools tab not displaying anything.

**Comment by Majpuc** [comment]
@sharoncy  Can you hide the tools tab in UI if nothing is active there?

**Comment by sharoncy** [comment]
I don't know how to do this @Majpuc , but would like to learn @leuat . We should probably implement this feature rather than remove it as it would be very useful for validation purposes. So I suggest we either implement this next week or hide it next week, whichever fits best with our other work commitments.

**Comment by Majpuc** [comment]
Any opinion @leuat ?

**Comment by sharoncy** [comment]
This has been removed from the GUI. Plan to implement at a later date.

**Comment by Majpuc** [comment]
Issue closed on 29.06.2020
