### ISSUE TITLE
Suggestion - option to give coordinate file same name as .nut file

### ISSUE THREAD

**Issue by marovst** [leuat/nutil#88]
It would be nice if the output coordinate file had the same name as the .nut file. This could be implemented either as an option for the user to chose himself or "forced" with no option to chose.

**Comment by sharoncy** [comment]
This is worth considering

**Comment by sharoncy** [comment]
The coordinate files and output images should have the NUT file name as a prefix. This has already been implemented for the reports.

**Comment by sharoncy** [comment]
This is done.

**Comment by Majpuc** [comment]
Validated MAP 10.06.2020
