### ISSUE TITLE
Standardise .cvs / report output

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#9]

**Comment by sharoncy** [comment]
Suggestions for report titles: 
Report_wholebrain_original (currently Report_combined.xlsx)
Report_sections_original (currently Report_slices.xlsx) 
Report_wholebrain_custom (currently Report.xlsx)
Report_sections_custom (currently Report_slices_summary.xlsx)
I have created a folder with suggestions for layout and will let you know when I am done.

**Comment by sharoncy** [comment]
Need to discuss with Nicolaas to understand how areasplitting/max objectsize affects object lists in reports - next friday

**Comment by sharoncy** [comment]
My final suggestions for report layout:
Report_RefAtlasRegions.xlsx
Report_CustomRegions.xlsx
Report_ObjectAreas.xlsx
The reports are located in Nutil_Package_beta\Optimal_output_layout

**Comment by sharoncy** [comment]
I have compared output of Nutil v0.32 (with AreaSplitting and no masks) to v0.03205. The numbers are identifical (slight differences in no. of decimal places used for calculations).

**Comment by sharoncy** [comment]
There are some small tweaks needed in the reports:  
-change some column headers, etc.
- remove object reports with areasplitting from ReportCustomRegionWholeBrain
-small discrepancies in total output with and without area splitting

**Comment by Majpuc** [comment]
Validated by Sharon 21 jan 2020
