### ISSUE TITLE
Nutil error - what's going on? 

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#91]
I tried to run quantifier and got a non-specific error. Any ideas? 

Z:\HBP_Analytics\Nutil_Quantifier\Allen_ISH_79556738_Pvalb_Validation\AllenParv_validation.nut

![NutilError](https://user-images.githubusercontent.com/30626642/74227764-6f6b7800-4cbf-11ea-8bcb-720e81df643e.PNG)

**Comment by leuat** [comment]
Thanks for producing this crash! hehe... pull a new version and marvel at the error message

**Comment by sharoncy** [comment]
CustomRegion template did not have colours specified.
