### ISSUE TITLE
HTML reports are not saved to the correct folders

### ISSUE THREAD

**Issue by sharoncy** [leuat/nutil#96]
CSV reports are automatically saved in CustomRegion, RefAtlasRegion and Object folders. HTML reports are not saved outside of these folders. 

![Foldererror](https://user-images.githubusercontent.com/30626642/74912910-e4296b00-53bf-11ea-91d1-b9c69036425c.PNG)

**Comment by leuat** [comment]
Fixed

**Comment by Majpuc** [comment]
Html reports now are going to the right folders but you get both CSV and Html when you choose html. Either we should change that, either you could explain in the help text that choosing html gives both type of results.

**Comment by Majpuc** [comment]
if you switch from csv to html, it will not delete any old files. 
Working properly. Validated 26.03.2020
