### ISSUE TITLE
Using VisuAlign flat files with quantifier for WHS v3

### ISSUE THREAD

**Issue by ingvildeb** [leuat/nutil#97]
When I try using flat files from VisuAlign with version 3 of the WHS atlas, the region IDs seem to be switched around so that the object counts are not assigned to the right regions. The colors are also changed in the output images.

VisuAlign output generated with WHS v2 works fine, and QuickNII output with WHS v3 also works. So the problem is specific to WHS v3 VisuAlign output files, I suppose. Not sure if the problem is with VisuAlign or Nutil, or if I am doing something stupid...

I put a folder with the input, output and atlas files here: Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\v3_quantifier_problem

**Comment by Majpuc** [comment]
I was able to reproduce this error. Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\v3_quantifier_problem\Output2_dir\ with Test_quant_WHSv3_MAP.nut file
Also custom reports are generated even if NO custom reports was chosen.

**Comment by sharoncy** [comment]
There is a lack of correspondence between the flat files/ label file for v3. Nutil uses the row numbers as the unique identifier (because this is what is used by the flat files - it is Gergely that has decided this). The row no. of the regions has changed in v3 relative to v2 but the flat files have not been updated to take this info account. Check with Gergely on the best course of action (he should either update the flat files, otherwise the label file has to be changed).

**Comment by sharoncy** [comment]
Ingvild also mentioned that Nutil did not extract coordinate files for her dataset. This occured as she did not use CustomRegions in her Nutil file. Nutil does not generate coordinates unless a CUstomRegion file is included (this defines the colour of the coordinates).

**Comment by sharoncy** [comment]
I have added the WHS_Atlas_Rat_Brain_v3.label file with erroneous label 44 to Nutil and have published a new version on the Nesys server: Z:\HBP_Analytics\Nutil\Nutil_releases\NutilInternal. Would you @ingvildeb be able to test if this has fixed the problem please?

**Comment by ingvildeb** [comment]
Sorry to say it does not seem to work, I tried both with QuickNII and VisuAlign maps. See Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\v3_quantifier_problem, .nut files: Test_quant_WHSv3_SY and Test_quant_WHSv3_visualign_IEB

**Comment by sharoncy** [comment]
This has now been fixed, with a new version released on the Nesys server.

**Comment by Majpuc** [comment]
Validated in v 0.402 on 26.03.2020
